### ISSUE TITLE
Additional terminal capaibility: ADDS25

### ISSUE THREAD

**Issue by sijnstra** [avalonbits/vdp-gl#14]
I am in need of the Agon to have additional terminal emulation, in particular the ADDS25 terminal, so I built it.

I've done the initial coding for the majority of the features. There are a few things I needed to add the ConvCtrl mappings, and there are 3 which I cannot find a primitive to map to, but they will not impact most use cases. It certainly works for my purpose (support of TRS-OS), and I think additional terminal mode support for additional terminal types will benefit other retro people out there.

Thoughts or concerns?

**Comment by avalonbits** [comment]
Send me a PR for review.

**Comment by sijnstra** [comment]
PR Merged
